### PR TITLE
Added create_qualitative_cmap function

### PR DESCRIPTION
**Pull request by abatten**
I have written a fairly simple function to turn any colormap into a qualitative one (i.e a single colour between two values).

I haven't written any tests for it, but I have run pytest on my computer and it doesn't seem to break anything (and passes flake8.

Let me know if there is anything I should change or fix before you can merge it. I wasn't sure about the naming style you would prefer for this function. I went with 'create', but I think 'make' or 'generate' would also work.

### CODE REVIEW

**Comment by 1313e** [comment]
@abatten Thx for the suggestion.

However, the function you have written always creates a colormap that has 256 segments.
A qualitative colormap should only have as many segments as it has colors.
Otherwise, the colors are not guaranteed to be spaced out properly.

I believe that a function like this, although useful, is not significant enough to warrant its own implementation.
For example, the same effect can be obtained using the following one-liner for obtaining a qualitative version of `rainforest` using its central 60% and 5 colors:
```python
cmr.register_cmap('rainforest_qual', cmr.take_cmap_colors('cmr.rainforest', 5, cmap_range=(0.2, 0.8)))
```
Another way is to simply modify the `get_sub_cmap` function to allow for the number of segments to be provided, similar to `take_cmap_colors`.

**Comment by 1313e** [comment]
If you feel like it, you could modify the `get_sub_cmap` function to behave in a similar way without having to add additional functions, and then I will happily accept a PR with those changes. :)

**Comment by abatten** [comment]
Thanks @1313e, I will get on this and make another pull request soon.

**Comment by 1313e** [comment]
The tests of `get_sub_cmap` are currently failing with the last changes you introduced: https://github.com/1313e/CMasher/pull/28/checks?check_run_id=1877197805

**Comment by 1313e** [comment]
As I have to modify the naming stuff anyway, I will just merge it.

**Pull request merged**
