### PR TITLE
GitHub Action to lint Python code

### PR DESCRIPTION
**Pull request by cclauss**
https://github.com/codespell-project/codespell#codespell

### CODE REVIEW

**Comment by 1313e** [comment]
Looks great, but what is the `--ignore-words-list="Mutch"` for?

**Comment by cclauss** [comment]
./joss_paper/paper.bib:3: Mutch ==> Much

**Comment by 1313e** [comment]
Oh, right.
Forgot about that one.

However, that shouldn't be the only word that does not require fixing, right?
After all, "cmashing" is a word I use in a few places, which is definitely not a valid word.

**Comment by cclauss** [comment]
codespell does not find all spelling mistakes (because code is not prose) but instead finds common spelling errors.
See https://github.com/codespell-project/codespell#codespell

**Comment by 1313e** [comment]
Alright, I am happy to accept this PR.

**Pull request merged**
