### PR TITLE
ENH: add stub file of cm.py and script that generates it

### PR DESCRIPTION
**Pull request by beskep**

### CODE REVIEW

**Comment by neutrinoceros** [comment]
for posterity: replaces #111 and fixes #110

**Comment by neutrinoceros** [comment]
Looks good, but you'll also need to make sure type-checking tests are passing. Actually it seems that most errors are "unused ignore comment" so that's great; please remove such comments and deal with other errors.

You may run the check locally as
```shell
$ python -m pip install -r requirements/typecheck.txt
$ python -m mypy cmasher
```

**Comment by beskep** [comment]
I haven't thought about that could cause a type checking error.

Also fixed implicit-str-concat warning that pylint was complaining about.

**Comment by neutrinoceros** [comment]
Good job, and congrats on your first merged PR ! 🎉

**Pull request merged**
